// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Carries the app-facing payload for worktree creation requests.
 */
export type CreateWorktreeRequest = {
  taskId: string;
  branchName: string | null;
  activity: WorktreeActivity;
};

/**
 * Returns the created worktree after a successful create request.
 */
export type CreateWorktreeResponse = { worktree: Worktree };

/**
 * Identifies which worktree to delete.
 */
export type DeleteWorktreeRequest = { worktreeId: string };

/**
 * Returns the deleted worktree identifier after a successful delete request.
 */
export type DeleteWorktreeResponse = { worktreeId: string };

/**
 * Identifies which worktree to fetch.
 */
export type GetWorktreeRequest = { worktreeId: string };

/**
 * Returns one worktree payload after a successful fetch.
 */
export type GetWorktreeResponse = { worktree: Worktree };

/**
 * Requests the full visible worktree list.
 */
export type ListWorktreesRequest = Record<symbol, never>;

/**
 * Returns the visible worktree list.
 */
export type ListWorktreesResponse = { worktrees: Array<Worktree> };

/**
 * Carries the full replacement payload for worktree updates in the first slice.
 */
export type UpdateWorktreeRequest = {
  worktreeId: string;
  taskId: string;
  branchName: string | null;
  activity: WorktreeActivity;
};

/**
 * Returns the updated worktree after a successful update request.
 */
export type UpdateWorktreeResponse = { worktree: Worktree };

/**
 * Describes the public worktree payload shared across adapter responses.
 */
export type Worktree = {
  id: string;
  taskId: string;
  branchName: string | null;
  activity: WorktreeActivity;
};

/**
 * Describes whether the public worktree view is active for its task.
 */
export type WorktreeActivity = "inactive" | "active";
