// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Carries the `fs/read_text_file` parameters an agent sends to the client.
 */
export type ReadTextFileRequest = {
  sessionId: string;
  path: string;
  /**
   * Starts the returned slice at this 1-based line instead of the first line.
   */
  line: number | null;
  /**
   * Limits the returned slice to this many lines.
   */
  limit: number | null;
};

/**
 * Returns the requested text file contents to the calling agent.
 */
export type ReadTextFileResponse = { content: string };

/**
 * Carries the `fs/write_text_file` parameters an agent sends to the client.
 */
export type WriteTextFileRequest = {
  sessionId: string;
  path: string;
  content: string;
};

/**
 * Acknowledges a completed text file write, which carries no result fields.
 */
export type WriteTextFileResponse = Record<symbol, never>;
