// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Carries the agent's complete plan for the current turn.
 *
 * Each update replaces the previous plan outright, so entries are never merged.
 */
export type Plan = { entries: Array<PlanEntry> };

/**
 * Describes one step the agent intends to take during the current turn.
 */
export type PlanEntry = {
  /**
   * Describes the step in human-readable form.
   */
  content: string;
  priority: PlanEntryPriority;
  status: PlanEntryStatus;
};

/**
 * Ranks how important one plan entry is relative to the rest of the plan.
 */
export type PlanEntryPriority = "high" | "medium" | "low";

/**
 * Describes how far the agent has progressed through one plan entry.
 */
export type PlanEntryStatus = "pending" | "in_progress" | "completed";
