// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A session configuration option.
 */
export type ConfigOption = {
  /**
   * The stable option identifier.
   */
  id: string;
  /**
   * The display name.
   */
  name: string;
  /**
   * An optional option description.
   */
  description?: string;
  /**
   * An optional semantic category.
   */
  category?: string;
  /**
   * The input control type.
   */
  type: ConfigOptionType;
  /**
   * The selected value.
   */
  currentValue: ConfigOptionCurrentValue;
  /**
   * Values required for a select option.
   */
  options?: Array<ConfigOptionValue>;
  /**
   * Optional extension data.
   */
  _meta?: Record<string, unknown>;
};

/**
 * The current value of a configuration option.
 */
export type ConfigOptionCurrentValue = string | boolean;

/**
 * The input control type for a configuration option.
 */
export type ConfigOptionType = "select" | "boolean";

/**
 * A selectable configuration value.
 */
export type ConfigOptionValue = {
  /**
   * The value identifier.
   */
  value: string;
  /**
   * The display name.
   */
  name: string;
  /**
   * An optional value description.
   */
  description?: string;
  /**
   * Optional extension data.
   */
  _meta?: Record<string, unknown>;
};

/**
 * Parameters for the `session/set_config_option` request.
 */
export type SetConfigOptionParams = {
  /**
   * The target session.
   */
  sessionId: string;
  /**
   * The configuration option to change.
   */
  configId: string;
  /**
   * The new configuration value.
   */
  value: ConfigOptionCurrentValue;
  /**
   * The option type required for a boolean value.
   */
  type?: ConfigOptionType;
  /**
   * Optional extension data.
   */
  _meta?: Record<string, unknown>;
};
