// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A selectable agent session mode.
 */
export type SessionMode = {
  /**
   * The stable mode identifier.
   */
  id: string;
  /**
   * The display name.
   */
  name: string;
  /**
   * An optional mode description.
   */
  description?: string;
  /**
   * Optional extension data.
   */
  _meta?: Record<string, unknown>;
};

/**
 * The current mode and available modes for a session.
 */
export type SessionModeState = {
  /**
   * The active mode identifier.
   */
  currentModeId: string;
  /**
   * The modes available to the agent.
   */
  availableModes: Array<SessionMode>;
  /**
   * Optional extension data.
   */
  _meta?: Record<string, unknown>;
};

/**
 * Parameters for the `session/set_mode` request.
 */
export type SetSessionModeParams = {
  /**
   * The target session.
   */
  sessionId: string;
  /**
   * The mode to activate.
   */
  modeId: string;
  /**
   * Optional extension data.
   */
  _meta?: Record<string, unknown>;
};
