// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A user-invokable slash command.
 */
export type AvailableCommand = {
  /**
   * The command name without a slash.
   */
  name: string;
  /**
   * The command description.
   */
  description: string;
  /**
   * Optional command input details.
   */
  input?: AvailableCommandInput;
  /**
   * Optional extension data.
   */
  _meta?: Record<string, unknown>;
};

/**
 * Input details for a slash command.
 */
export type AvailableCommandInput = {
  /**
   * The prompt shown before input is provided.
   */
  hint: string;
  /**
   * Optional extension data.
   */
  _meta?: Record<string, unknown>;
};
