// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Requests a new terminal running one command for the session.
 */
export type CreateTerminalRequest = {
  sessionId: string;
  command: string;
  /**
   * Passes command arguments verbatim without shell interpretation.
   */
  args: Array<string>;
  /**
   * Adds environment variables on top of the client environment.
   */
  env: Array<EnvVariable>;
  /**
   * Runs the command in this absolute directory instead of the client default.
   */
  cwd: string | null;
  /**
   * Retains at most this many output bytes, truncating older output first.
   */
  outputByteLimit: bigint | null;
};

/**
 * Returns the identifier of the terminal that was created.
 */
export type CreateTerminalResponse = { terminalId: string };

/**
 * Carries one environment variable applied to a terminal command.
 */
export type EnvVariable = { name: string; value: string };

/**
 * Requests termination of the running command while keeping the terminal readable.
 */
export type KillTerminalRequest = { sessionId: string; terminalId: string };

/**
 * Acknowledges a completed kill, which carries no result fields.
 */
export type KillTerminalResponse = Record<symbol, never>;

/**
 * Requests release of the terminal and every resource it still holds.
 */
export type ReleaseTerminalRequest = { sessionId: string; terminalId: string };

/**
 * Acknowledges a completed release, which carries no result fields.
 */
export type ReleaseTerminalResponse = Record<symbol, never>;

/**
 * Describes how a terminal command finished once it is no longer running.
 */
export type TerminalExitStatus = {
  /**
   * Reports the process exit code, absent when a signal terminated the process.
   */
  exitCode: number | null;
  /**
   * Names the signal that terminated the process, absent on a normal exit.
   */
  signal: string | null;
};

/**
 * Requests the output captured so far without waiting for the command to finish.
 */
export type TerminalOutputRequest = { sessionId: string; terminalId: string };

/**
 * Returns the captured terminal output and the command status at capture time.
 */
export type TerminalOutputResponse = {
  output: string;
  /**
   * Reports whether output was dropped to stay within the byte limit.
   */
  truncated: boolean;
  /**
   * Describes the exit, absent while the command is still running.
   */
  exitStatus: TerminalExitStatus | null;
};

/**
 * Requests a wait until the terminal command finishes.
 */
export type WaitForTerminalExitRequest = {
  sessionId: string;
  terminalId: string;
};

/**
 * Returns how the terminal command finished.
 */
export type WaitForTerminalExitResponse = {
  /**
   * Reports the process exit code, absent when a signal terminated the process.
   */
  exitCode: number | null;
  /**
   * Names the signal that terminated the process, absent on a normal exit.
   */
  signal: string | null;
};
